name: pragma_test
description: "A project developed for technical test in pragma company"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #Logic
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  http: ^1.4.0

  #Environment
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - .env
